[build]
  # Since this is a static site, no build command needed
  publish = "."

[build.environment]
  # Node version for any future serverless functions
  NODE_VERSION = "18"

# Redirect rules for SPA behavior (optional)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/styles.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/script.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"